### ISSUE TITLE
"Hide post title" setting not working in Gutenberg

### ISSUE THREAD

**Issue by rsolvang** [sukiwp/suki#10]
The post title won't hide when I select it in the Customizer, using the Gutenberg editor.
![Gutenberg options panel](https://user-images.githubusercontent.com/1956027/45678347-79269580-bb36-11e8-8fd1-73e53e49a7c9.png)

This happens on a clean, newly installed WP install.

**Comment by daviedR** [comment]
Hi @rsolvang , I will check it soon.

**Comment by daviedR** [comment]
This will be fixed on v0.5.3. Will upload soon :)

**Comment by daviedR** [comment]
Fixed
