### ISSUE TITLE
Thread for v1.3.0-beta

### ISSUE THREAD

**Issue by daviedR** [sukiwp/suki#103]
Hi guys, I just uploaded the first beta version of v1.3.0, which is a huge update for us. You can download the first beta here: https://github.com/sukiwp/suki/releases/download/1.3.0-beta/suki-1.3.0-beta.zip

THIS IS NOT A PRODUCTION VERSION, Please only use for testing, not for live websites.

Changelog:

- NEW: Hero Section - Replace the former "Page Header" section.
- NEW: Dedicated Single Post Page options (formerly uses the same layout as "Default" post layout for archives page).
- NEW: Dedicated Single Static Page options (formerly uses the same layout as "Default" post layout for archives page).
- NEW: Native breadcrumb module.
- NEW: Header Elemets — Add new options to show Shopping Cart's amount and its responsive visibility.
- NEW: Social Icons — Add more social icons: WordPress, Messenger, Skype, Slack, Telegram, WhatsApp, GitLab, Bitbucket.
- NEW: Sidebar - Add new option to set widget title tag (h2 / h3 / h4 / div) for custom SEO needs.
- NEW: Footer Widgets Bar - Add new option to set widget title tag (h2 / h3 / h4 / div) for custom SEO needs.
- NEW: Gutenberg - Add new theme supports for Gutenberg features: theme font sizes, custom line height, custom units, custom cover block padding, custom link color.
- NEW: Footer Elements — Add new element: HTML (accepts HTML tags and shortcode).
- NEW: Border radius and Box shadow options for posts layout, sidebar.
- NEW: WPML Compatibility - Add WPML configuration file (`wpml-config.xml`) for automatic WPML integration.
- TWEAK: Header Elements — SVG Logo now will be displayed using `<img>` tag instead of the inline SVG method. This will prevent display issue when both desktop and mobile SVG logo contain elements with same ID (e.g. gradient fill effect).
- TWEAK: Header Elements — Improve header's Shopping Cart template (**If you overrode this template via Child Theme, please review the template again**).
- TWEAK: Header Elements — Allow "Shopping Cart Dropdown" inside the mobile header bar.
- TWEAK: Header Builder — Improve header menu javascript to support full width Mega Menu (available since Suki Pro v1.2).
- TWEAK: Social Icons — Update some existing social icons.
- TWEAK: Social Icons — Add hidden label on each social icon for better accessibility.
- TWEAK: Social Icons — Remove Google+.
- TWEAK: Google Fonts — Update Google Fonts list.
- TWEAK: WooCommerce compatibility — Improve mini cart widget's buttons CSS (make each button full width for better compatibility with longer text in non-english languages).
- TWEAK: Elementor compatibility — Move compatibility CSS to standalone inline CSS. 
- TWEAK: Customizer — Improve Customizer UI & UX.
- TWEAK: Theme Dashboard — Improve theme dashboard layout for better compatibility with Suki Pro's White Label module. Now user won't see "pro" badges and links to our website on the modules manager.
- TWEAK: Deprecate "Page Header" section.
- FIX: Header — Shopping cart dropdown toggle does nothing on Cart and Checkout pages. Now it works like a link to the Cart page.
- FIX: WooCommerce — "My Account" page's navigation links color doesn't follow the global link color configured in Customizer.
- FIX: Elementor Pro compatibility — Elementor Pro's WooCommerce products grid CSS conflict with theme's CSS.
- FIX: Customizer Preview Frame size for Tablet and Mobile modes.

TODO:

- Improve Customizer UX to prevent ambiguous options.
- Provide fallback compatibility for Suki Pro 1.1.x version.
- Check migration from "Page Header" to Hero Section.
- Fix any possible bugs.

**Comment by drenina** [comment]
Copied from the Facebook group:

**Bugs**

- vertical toggle not displayed on desktop (only on tablets and mobile)
- grid blog layout broken; entry excerpt is not aligned
- theme default breadcrumbs are not displayed when regular page title is enabled (only with the page header bar they are displayed)

**Feature requests/Feedback**

- changing the html font-color to a more multipurpose black instead of blueish scheme
- changing html font-size to 16px which is browser default

**Comment by daviedR** [comment]
Thanks @drenina
