### ISSUE TITLE
Breadcrumbs Woocommerce

### ISSUE THREAD

**Issue by drenina** [sukiwp/suki#118]
The Woocommerce breadcrumb structure on archives is not correct. It is displaying the categories/subcategories first, then "Home", and then "Shop". "Home" should be first, then "Shop", and then the category/subcategory,

**Comment by daviedR** [comment]
Hi @drenina, We just released a new update that fixed the breadcrumb bugs, please review this issue again.

**Comment by drenina** [comment]
@daviedR Which version are you talking about? The problem still exists in 1.3.3.

**Comment by daviedR** [comment]
We just released another update, v1.3.4 which fixed this issue.
