### ISSUE TITLE
issues v0.6.0

### ISSUE THREAD

**Issue by r0r0z** [sukiwp/suki#17]
- not able to translate search placeholder because default text domain is "default". Maybe override default search form in theme can solve the issue

- the woocommerce buttons like add to cart, place order and update cart are not inheriting the border-style and color from the customizer default button settings
add to cart, View cart, checkout, proceed to checkout tidak ikut warna button global. 
add to cart and proceed to checkout button can be change from customizer > woocommerce > alt button (but the default value of alt button on hover doesn't work). If you change to other color, the hover color works. if you set back the hover color to default (default button click), customizer live preview shows the correct color (default) but if you refresh the page or go to the page, the hover color setting doesn't work (using woocommerce default color). View cart and checkout button in pop up mini cart are not inheriting the color from global button setting neither woocommerce alt button setting.

- cart table on mobile: certain table rows have a double border because the td as well as the table has a border set in the css

- dropdown cart menu is not align properly
it happened if subtotal translated text and the total amount is too long. It can be solved with custom css min-width. another issue is the product title will through the product image.

**Comment by daviedR** [comment]
> not able to translate search placeholder because default text domain is "default". Maybe override default search form in theme can solve the issue

Search placeholder is a default text from WordPress.

**Comment by daviedR** [comment]
The others were fixed on these commit: https://github.com/sukiwp/suki/commit/75aa2897ba2d516584babdea485aea0298d1a5d1 and https://github.com/sukiwp/suki/commit/c659cbf2483a8c592fc7fcdc72658e04f756ba7b

**Comment by daviedR** [comment]
> not able to translate search placeholder because default text domain is "default". Maybe override default search form in theme can solve the issue

fixed on commit https://github.com/sukiwp/suki/commit/293880a5f7806edf2c4883ed7629117648a87a50
