### ISSUE TITLE
Comment Area on responsive is not wrapped

### ISSUE THREAD

**Issue by cuongtalentccc** [sukiwp/suki#32]
The comment is out of the screen.

**Comment by daviedR** [comment]
Can you share a URL to check on? I checked on my local site but it works fine.

**Comment by cuongtalentccc** [comment]
Hi @daviedR,
I attached 2 screenshots to show the issue (**Comment Area** & **Footer Bar**)
https://cl.ly/ce5a89
https://cl.ly/d6b54d

You can check at URL: https://askusecase.com/2018/10/07/how-to-increase-your-business-exposure-with-seo/

**Comment by daviedR** [comment]
Okay thanks!
It will be fixed in next version.

**Comment by daviedR** [comment]
Fixed on fbb29230cb723ee33a745c615a2ad8945fa0e129
