### ISSUE TITLE
Bottom Bar is blank in responsive if choose Contained Section

### ISSUE THREAD

**Issue by cuongtalentccc** [sukiwp/suki#33]
If I choose Contained Section for Bottom Bar, in mobile it is blank.

https://cl.ly/512258 (mobile view)
https://cl.ly/d319a2 (desktop view - it's fine)

URL for check: https://askusecase.com

**Comment by daviedR** [comment]
Fixed on https://github.com/sukiwp/suki/commit/b2ba3db65542e2322f0e504f90150790faa15a5a
