### ISSUE TITLE
Page Builder Elementor (Brizy included) is weird in backend

### ISSUE THREAD

**Issue by cuongtalentccc** [sukiwp/suki#34]
Any time I create a page with Page Builder plugin as Elementor, Brizy, etc the backend change font-family and font-size. It is weird.

Screenshot: https://cl.ly/7ef687

**Comment by daviedR** [comment]
This is fixed on https://github.com/sukiwp/suki/commit/14fedf4f061dd1628985c5221ce3cfc27b04abc1

The upcoming v1.0.0 will have this issue fixed.
