### ISSUE TITLE
Woocommerce second image on hover is stretched

### ISSUE THREAD

**Issue by yratof** [sukiwp/suki#59]
When enabling the second image, it's stretches to 100% height, 100% width.

Default behaviour could be to set it to cover:

```
.woocommerce ul.products li.product .suki-product-thumbnail.suki-product-thumbnail-alt-hover-image a img:nth-child(2) {
object-fit: cover;
}
```

**Comment by daviedR** [comment]
Hi @yratof 

Did you mean the "WooCommerce Alt Hover Image" mode?

**Comment by daviedR** [comment]
Hi @yratof 

I will close this issue for now. Feel free to reopen it if you still have the issues.

**Comment by yratof** [comment]
Sorry I only just noticed the reply, I did yes. I've updated to Suki 1.1 today and that image doesn't seem to be a problem now, maybe you fixed already?
