### ISSUE TITLE
Grid view markup h2 vs h3

### ISSUE THREAD

**Issue by AlchemyUnited** [sukiwp/suki#60]
Suki: Version: 1.0.14

Using the blog grid view the title is wrapped in an h2 tag, but the class="entry-small-title h3"  I presume that h3 class should be an h2.

**Comment by daviedR** [comment]
No, the h3 class is intentional. The blog grid title is a "small title". And "small title" inherits h3 styles by default, but can be overridden using the options on `General Styles > Small Title`. 

So we are using h2 for SEO purpose because it's structurally correct. But for styles, it will inherit from h3 by default.

**Comment by AlchemyUnited** [comment]
Ok. I get it :) Makes sense but the class nanes make it confusing ;)

A couple of thoughts if you don't mind:

1) Don't output the .h3 in the markup class=" ". and when you're outputting the CSS .h3 do 

.small-title, .h3{
 ...properties...
}

then IF the .small-title is defined in Gen Ele > Small Title just be sure it's output in the CSS after the .small-title, .h3{ } and the "newer" small-title  will be used. So instead of inheritance, use CSS cascading to override, if desired. Same result but slightly clear markup. 

Again, I get what you did. It's just a bit confusing because there's an h3 class in an h2 heading.  :)

2) fwiw, technically, headline tags are semantic. That is, they are mostly for search engines and screen readers. Their styling should be independent (tho' few people do it this way - they should).  So you could have had a section for setting the font-sizes. Say something like

largest
larger
large
default
small
smaller
smallest

 And then for the headings you'd select one of those. For example, h2 could be large, but h3 larger.  Kinda like you did above. That is, to abstract the font settings away from the heading and into their own class. The benefit is, say .largest could be used elsewhere and it would remain consistent but ultimately independent of the heading. Styling and semantic remain independent, as they should be ;)

<h1 class="largest>...</h1>

I think you could still do this and be backward compatible. 

p.s. How do you feel about adding vw and vh for font sizing?

**Comment by daviedR** [comment]
Hi @AlchemyUnited 

2. I think that would be more confusing, especially for a beginner. In common manners, the size of headings typography would follow down to the heading level itself. For example, H2 is larger than H3, and H3 is larger than H4.

I get your points, but I don't think it would make things easier, especially for a new user.

Imagine that when first time using this theme, you are being asked "What is your largest typography style?", "What is your smallest typography style?".And then in the Headings typography, you will be asked again "What typography size do you want to use for H2?".

I think that flow is more complicated for users.

**Comment by daviedR** [comment]
Hi @AlchemyUnited

I would think of something for the `title` and `small-title` inheritance system. Practically, we can remove the `h3` class on blog post grid title, but I will see if it leads to some issues.

---

About the "largest, larger, large, default, small, smaller, smallest" typography settings:

I think that would be more confusing, especially for a beginner. In common manners, the size of headings typography would follow down to the heading level itself. For example, H2 is larger than H3, and H3 is larger than H4.

I get your points, but I don't think it would make things easier, especially for a new user.

Imagine, you are being asked "What is your largest typography style?", "What is your smallest typography style?". You will wonder, what is this for? And then in the Headings typography, you will be asked again "What typography size do you want to use for H2?", "What typography size do you want to use for H3?".

I think this flow is more complicated for users.

**Comment by AlchemyUnited** [comment]
"Imagine, you are being asked "What is your largest typography style?", "What is your smallest typography style?". You will wonder, what is this for?"

Well, yeah, that would have to explained. But because it's not super simple doesn't mean it doesn't matter. But because of the general crammed (?) nature of the WP Customizer such things aren't easy. That doesn't mean they shouldn't be done. Does it :)

I mean, is this any difference than knowing what heading tags are any why they matter? Do most new users understand that? Would they understand font sizes? I actually think the latter is more true ;)

"I think this flow is more complicated for users."

Yes and no. I think the key advantage - which I didn't mention earlier - is the defined sizes could be used with your Blocks. As it is, there's no way to communicate such things from theme to blocks. 

If you had font size settings (say XS, SM, MD, LG, XL, XXL) you could have inherited defaults for headings. H1 = XXL, H2, = XL, etc. If the use doesn't want to set them, they don't have to, you have defaults. 

I think it would be good / great is there was a relationship between Suki font sizes and Gutenberg's add_theme_support option for setting font sizes ANd have that tied to headings.  

I'm not expecting anything in Suki to change. This is more philosophical/theoretical for me.  I believe that if you gave it come thought you'd find an answer that would make better sense. Sizes are sizes. They have a use. Heading are heading and they're only sized out of convenience, not because they should be. 

p.s. It's a shame the Customizer isn't more like a wizard. That is, more question driven. 

"What is the size of your title?"

"What is the size of _____" 

That is, it leads you thought the process. The whole drill down and backup again...that's a wonky UX. Hopefully someday they'll address this :)
