### ISSUE TITLE
Exporting Suki settings?

### ISSUE THREAD

**Issue by AlchemyUnited** [sukiwp/suki#61]
I've setup a Suki-based theme locally.  I don't want / need to export my whole local code+DB, just the Suki theme settings.  I am aware there's an Suki import (plugin) but is there also an export? 

If there's not a formal export process, what are the WP option (table) key names that I should look for? Worst case, maybe I can do a manual copy from one DB to the other?

 Or maybe there's a way for me to piggy-back on the import plugin?

p.s. Ultimately, I'd be interested in a way of doing the settings via a PHP file. That is, instead of fumbling around in the customizer, I could pre-define the settings via PHP and import that as my own set of defaults (instead of the "generic" Suki defaults).  To some extent, this would also serve as a backup for the theme (in case the client muck it up I can restore the theme back to where it started without having to mess with the entire DB).

Thanks in advance for your help.

**Comment by daviedR** [comment]
Hi @AlchemyUnited 

We use native `theme_mods` API from WordPress, that means the whole Customizer settings are saved in the `theme_mods_suki` option.

The Suki Sites Import is only for predefined demo sites that we released. It doesn't have manual import mode.

To export and import, you can use plugin like [Customizer Export / Import](https://wordpress.org/plugins/customizer-export-import/).

As for the predefined settings, I think you could use our filters API. So, the idea is you can define your own settings as default values. The filter is `suki/customizer/setting_defaults`.

We use this same method to populate our default values, so you can easily override them using higher priority when adding your own filter.

**Comment by AlchemyUnited** [comment]
1)  Customizer Export / Import. === thank you!

2) suki/customizer/setting_defaults. === thanks you!!!!

Is there any place to find a list of all the Suki customizer settings? Are they in on place by any chance?

**Comment by daviedR** [comment]
> Is there any place to find a list of all the Suki customizer settings? Are they in on place by any chance?

Unfortunately no.
