### ISSUE TITLE
SUki pro notice giving error with array_push

### ISSUE THREAD

**Issue by yratof** [sukiwp/suki#70]
wp-content/plugins/suki-pro/inc/class-suki-pro-notice.php line 119 has an error regarding array_push requiring two options

**Comment by yratof** [comment]
Cancel this. Suki pro deactivated itself

**Comment by yratof** [comment]
Wait, is Suki Pro not compat with latest Suki? 1.0.8 has errors

`wp-content/plugins/suki-pro/inc/class-suki-pro-notice.php` line `119` has an error regarding `array_push` requiring two options

**Comment by daviedR** [comment]
Hi @yratof 

Thanks for the report for Suki Pro issue. We will have a look at it and fix it in the next version.
I will close this thread because this "Issues" list is only for Suki (theme).

Regards,
David
