### ISSUE TITLE
"Scroll to Top"Button didn't work when choose Static display

### ISSUE THREAD

**Issue by cuongtalentccc** [sukiwp/suki#72]
The button Scroll to Top will not work if I choose the option "static" display.
![image](https://user-images.githubusercontent.com/26053333/67829724-c5e6e900-fb0a-11e9-9bfb-c1fb82100c96.png)

**Comment by daviedR** [comment]
Hi @cuongtalentccc 

I can confirm that the "static" Scroll to Top button works fine. Can you share your page URL?

**Comment by cuongtalentccc** [comment]
My mistake, close the issue!
