### ISSUE TITLE
Login user cannot see the post in correctly style

### ISSUE THREAD

**Issue by cuongtalentccc** [sukiwp/suki#73]
The front-end and login users are seeing the post differently because of font style are not match.

Preview feature is the same case that I cannot see correctly how the site shows visitors.

**Comment by daviedR** [comment]
What do you mean? Is there any URL that we can look into?

Have you tried clearing your cache?

**Comment by cuongtalentccc** [comment]
Sorry, it's my local plugin breaks the Suki theme. Close the issue!
