### ISSUE TITLE
Gutenberg image block: alignment wide

### ISSUE THREAD

**Issue by AlchemyUnited** [sukiwp/suki#78]
Full-width works fine. I get edge to edge. 

Alignment: Left, center and right, all seem fine as well. 

But alignment:  Wide width isn't even full width of the main content container/wrapper. There a class alignwide for the <figure> but nothing in the CSS to make that magic happen. 

I'll fix mine on my own, but I wanted to let you know.

**Comment by daviedR** [comment]
Hi @AlchemyUnited 

What content layout do you use? Narrow or Wide?

**Comment by daviedR** [comment]
Hi @AlchemyUnited 

I will close this thread to keep the issues list clean. If you feel this is still an issue, please feel free to re-open.
