### ISSUE TITLE
Stop autocompleting color in color pickers

### ISSUE THREAD

**Issue by luizbills** [sukiwp/suki#9]
If I type `#f3f` the color pickers autocompletes to `#ff33ff`, but I wanted to type `#f3f3f3`. It's very annoying :/

**Comment by daviedR** [comment]
It's default behavior of Iris color picker from WordPress. I agree it's very annoying :(

**Comment by daviedR** [comment]
This issue has been fixed on commit a7ab7b57d7e2af18a14508d27ce5730d1897810f (released on v0.6.0)
