### ISSUE TITLE
Script Error, when opening submenu on a mobile device

### ISSUE THREAD

**Issue by Nitrael86** [sukiwp/suki#93]
Since the update to Suki 1.2.9 opening the submenu on a mobile device does not work anymore. There is a script error.

main.min.js?ver=1.2.9:1 Uncaught ReferenceError: duration is not defined
    at Object.slideDown (main.min.js?ver=1.2.9:1)
    at HTMLDocument.e (main.min.js?ver=1.2.9:1)

**Comment by daviedR** [comment]
HI @Nitrael86 

We just uploaded a new version 1.2.10 that should have fixed this issue.
